In [2]:
import numpy as np

In [7]:
#################################  Main code #####################################
def Gauss(A, b):
    ''' 
    定义函数Gauss(A,b)
    Input:
    系数矩阵A: type = array 需要求解的方程组的系数矩阵
    常数矩阵b: type = array 需要求解的方程组的常数列
    Output:
    xi:    type = array(i = 1,2,……,n) 方程组的解向量
    '''
    #initialization
    A = A.copy()
    b = b.copy()
    m,n = A.shape                                       
    if m != n:                                          
        return 'No unique solution'                           
    x = np.zeros(n)                                     
    l = np.zeros((n,n))                                 
    #elimination
    for k in range(n - 1):                              
        if A[k][k] == 0:                                
            return 'Error Input'                        
        for i in range(k+1,n):                          
            l[i][k] = A[i][k] / A[k][k]                 
            for j in range(n):                          
                A[i][j] = A[i][j] - l[i][k] * A[k][j]   
            b[i] = b[i] - l[i][k] * b[k]                
        #print(A)                                       
    x[n - 1] = b[n - 1] / A[n - 1][n - 1]               
    #recursive
    for i in range(n - 2, -1, -1):                      
        for j in range(i + 1, n):                       
            b[i] -= A[i][j] * x[j]                      
        x[i] = b[i] / A[i][i]                        
    x = x.reshape(n,)
    return x

###################################  Test  code #####################################
if __name__ == '__main__':
    A = np.array([[3,1,2], [6, 3 ,4], [3, 2, 5]])
    b = np.array([11,24,22])
    x = Gauss(A, b)
    print("解为",x)
    print("Gauss消去计算方程组的残差的2范数为：",np.linalg.norm(A@x-b))
    print("解为",x)
    print("LU分解计算方程组的残差的2范数为：",np.linalg.norm(A@x-b))

解为 [1. 2. 3.]
Gauss消去计算方程组的残差的2范数为： 0.0
解为 [1. 2. 3.]
LU分解计算方程组的残差的2范数为： 0.0


In [4]:
# LU分解
import numpy as np

def LU_Doolittle_decomp(A):
    n,m = A.shape[0],A.shape[1]

    if n != m:
        return 'error dimension'
    L = np.eye(n)
    U = np.zeros((n,n))
    U[0,:] = A[0,:]
    for i in range(n):
        L[i,0] = A[i,0]/U[0,0]
    for i in range(1,n):
        for j in range(i,n):
            U[i,j] = A[i,j] - np.dot(L[i,:i],U[:i,j])
            if(j+1<n):
                L[j+1,i] = (A[j+1,j] - np.dot(L[j+1,:i],U[:i,i]))/U[i,i]
    # for k in range(n):
    #     for j in range(k,n):
    #         temp1 = 0
    #         for s in range(k-1):
    #             temp1 += L[k,s]*U[s,j]
    #         U[k,j] = A[k,j] - temp1
    #     for i in range(k+1,n):
    #         temp2 = 0
    #         for j in range(k-1):
    #             temp2 += L[i,s]*U[s,k]
    #         L[i,k] = (A[i,j] - temp2)/U[k,k]

    return L,U

if __name__ == '__main__':
    A = np.array([[3,1,2], [6, 3 ,4], [3, 2, 5]])
    L,U=LU_Doolittle_decomp(A)
    print(L)
    print(U)
    print(np.matmul(L,U))

[[1. 0. 0.]
 [2. 1. 0.]
 [1. 1. 1.]]
[[3. 1. 2.]
 [0. 1. 0.]
 [0. 0. 3.]]
[[3. 1. 2.]
 [6. 3. 4.]
 [3. 2. 5.]]


In [4]:
# LU分解
import numpy as np
def LU_Doolittle_decomp(A,b):
    ''' 
    定义函数LU(A,b)
    Input:
    系数矩阵A: type = array 需要求解的方程组的系数矩阵
    常数矩阵b: type = array 需要求解的方程组的常数列
    Output:
    xi:    type = array(i = 1,2,……,n) 方程组的解向量
    '''
    A = A.copy()
    b = b.copy()
    n,m = A.shape[0],A.shape[1]
    y = np.zeros((n,1))
    x = np.zeros((n,1))

    if n != m:
        return 'error dimension'
    L = np.eye(n)
    U = np.zeros((n,n))
    U[0,:] = A[0,:]
    for i in range(n):
        L[i,0] = A[i,0]/U[0,0]
    for i in range(1,n):
        for j in range(i,n):
            U[i,j] = A[i,j] - np.dot(L[i,:i],U[:i,j])
            if(j+1<n):
                L[j+1,i] = (A[j+1,j] - np.dot(L[j+1,:i],U[:i,i]))/U[i,i]
    print(L)
    print(U)
    
    #向前回代求解Ly=b
    y[0] = b[0]/L[0,0]
    for i in range(1,n):
        for j in range(i):
            b[i] = b[i] - L[i,j]*y[j]
        y[i] = b[i]/L[i,i]

    #向前回代求解Ux=y
    x[n-1] = y[n-1]/U[n-1,n-1]
    for i in range(n-2,-1,-1):
        for j in range(n-1,i,-1):
            y[i] = y[i] - U[i,j]*x[j]
        x[i] = y[i]/U[i,i]
    x = x.reshape(n,)

    return x

if __name__ == '__main__':
    A = np.array([[3,1,2], [6, 3 ,4], [3, 2, 5]])
    b = np.array([11,24,22])
    x = LU_Doolittle_decomp(A,b)
    print("解为",x)
    print("LU分解计算方程组的残差为：",np.linalg.norm(A@x-b))

[[1. 0. 0.]
 [2. 1. 0.]
 [1. 1. 1.]]
[[3. 1. 2.]
 [0. 1. 0.]
 [0. 0. 3.]]
解为 [1. 2. 3.]
LU分解计算方程组的残差为： 0.0


In [ ]:
def Hilbert_Matrix(i,j):
    H = np.zeros((i,j))
    for i in range(1,i+1):
        for j in range(1,j+1):
            H[i-1,j-1] = 1/(i+j-1)
    return H

H_12 = Hilbert_Matrix(12,12)
H_20 = Hilbert_Matrix(20,20)
b_12 = H_12@np.ones((12,1))
b_20 = H_20@np.ones((20,1))

x=LU_Doolittle_decomp(H_20,b_20)
print("LU分解求解结果:")
print(x)
print("LU分解残差:")
print(np.linalg.norm(H_20@x-b_20))
x = Gauss(H_20, b_20)
print("Gauss求解结果:")
print(x)
print("Gauss残差:")
print(np.linalg.norm(H_20@x-b_20))
